name: LobbyPaintball
version: 1.2-b1
authors: [CPx1989]
description: Just another paintball plugin...Revamped!
main: com.cpx1989.lpb.Paintball
softdepend:
 - VanishNoPacket
commands:
  lpb:
    description: LobbyPaintball
    aliases: lp
permissions:
  lpb.reload:
    default: false
  lpb.moveinventory:
    default: false
  lpb.staff:
    default: false
    children:
      - lpb.moveinventory
      - lpb.reload