Options:
  Announce: 10
  Limit: 20
  TitleTimer: 20
  Regen_Time: 20
  Paint: true
  RandomPerBlock: false
  Paint_Radius: 3
  SpigotHack: false
  Set_Item: true
  ClearOnJoin: true
Items:
  '1':
    Name: "&1&9&8&9&bSnow&3Shot"
    Lores:
      - &6Shoot snowballs out of the bow!"
      - "&1 "
      - "&aShoot players to earn points"
      - "&aor shoot blocks to color them!"
    Material: "IRON_HORSE_ARMOR"
    Type: SINGLE
    Power: 2
    Cooldown: 3
    Permission: "lpb.snowshot"
  '2':
    Name: "&9&8&9&1&bBurst&3Shot"
    Lores:
      - "&6Burst Fires snowballs out of the bow!"
      - "&1 "
      - "&aShoot players to earn points"
      - "&aor shoot blocks to color them!"
    Material: "GOLDEN_HORSE_ARMOR"
    Type: BURST
    Spread: 0.2
    Shots: 5
    Power: 2
    Cooldown: 10
    Permission: "lpb.burstshot"
  '3':
    Name: "&1&9&8&9&bRapid&3Shot"
    Lores:
      - "&6Rapid Fires snowballs out of the bow!"
      - "&1 "
      - "&aShoot players to earn points"
      - "&aor shoot blocks to color them!"
    Material: "DIAMOND_HORSE_ARMOR"
    Type: RAPID
    Shots: 8
    Power: 2
    Speed: 0.3
    Cooldown: 60
    Permission: "lpb.rapidshot"
  '4':
    Name: "&1&9&8&9&5Disco&3Stick"
    Lores:
      - "&6Hit players to send"
      - "&6them flying very far"
    Material: "STICK"
    Type: STICK
    Power: 50
    Cooldown: 5
    Permission: "lpb.staff"
  OPTIN:
    Name: "&1&9&8&9&aPlay Paintball"
    Lores: 
      - "&6Right click to play paintball!"
    Material: "NETHER_STAR"
    Type: OPTIN
    Cooldown: 10
  OPTOUT:
    Name: "&1&9&8&9&cLeave Paintball"
    Lores: 
      - "&6Right click to leave paintball!"
    Material: "NETHER_STAR"
    Type: OPTOUT
    Cooldown: 10
Layout:
  '0': 1
  '1': 2
  '2': 3
  '3': 4
  '5': OPTIN
Blocks:
  - "ACACIA_LEAVES"
  - "ACACIA_LOG"
  - "ACACIA_PLANKS"
  - "ACACIA_SLAB"
  - "ACACIA_STAIRS"
  - "ACACIA_WOOD"
  - "ANDESITE"
  - "ANDESITE_SLAB"
  - "ANDESITE_STAIRS"
  - "ANDESITE_WALL"
  - "BIRCH_LEAVES"
  - "BIRCH_LOG"
  - "BIRCH_PLANKS"
  - "BIRCH_SLAB"
  - "BIRCH_STAIRS"
  - "BIRCH_WOOD"
  - "BLACK_CONCRETE"
  - "BLACK_GLAZED_TERRACOTTA"
  - "BLACK_STAINED_GLASS"
  - "BLACK_TERRACOTTA"
  - "BLACK_WOOL"
  - "BLUE_CONCRETE"
  - "BLUE_GLAZED_TERRACOTTA"
  - "BLUE_ICE"
  - "BLUE_STAINED_GLASS"
  - "BLUE_TERRACOTTA"
  - "BLUE_WOOL"
  - "BONE_BLOCK"
  - "BOOKSHELF"
  - "BRAIN_CORAL_BLOCK"
  - "BRICK_SLAB"
  - "BRICK_STAIRS"
  - "BRICK_WALL"
  - "BRICKS"
  - "BROWN_CONCRETE"
  - "BROWN_GLAZED_TERRACOTTA"
  - "BROWN_MUSHROOM_BLOCK"
  - "BROWN_STAINED_GLASS"
  - "BROWN_TERRACOTTA"
  - "BROWN_WOOL"
  - "BUBBLE_CORAL_BLOCK"
  - "CARVED_PUMPKIN"
  - "CHISELED_QUARTZ_BLOCK"
  - "CHISELED_RED_SANDSTONE"
  - "CHISELED_SANDSTONE"
  - "CHISELED_STONE_BRICKS"
  - "CLAY"
  - "COAL_BLOCK"
  - "COAL_ORE"
  - "COARSE_DIRT"
  - "COBBLESTONE"
  - "COBBLESTONE_SLAB"
  - "COBBLESTONE_STAIRS"
  - "COBBLESTONE_WALL"
  - "CRACKED_STONE_BRICKS"
  - "CRAFTING_TABLE"
  - "CUT_RED_SANDSTONE"
  - "CUT_RED_SANDSTONE_SLAB"
  - "CUT_SANDSTONE"
  - "CUT_SANDSTONE_SLAB"
  - "CYAN_CONCRETE"
  - "CYAN_GLAZED_TERRACOTTA"
  - "CYAN_STAINED_GLASS"
  - "CYAN_TERRACOTTA"
  - "CYAN_WOOL"
  - "DARK_OAK_LEAVES"
  - "DARK_OAK_LOG"
  - "DARK_OAK_PLANKS"
  - "DARK_OAK_SLAB"
  - "DARK_OAK_STAIRS"
  - "DARK_OAK_WOOD"
  - "DARK_PRISMARINE"
  - "DARK_PRISMARINE_SLAB"
  - "DARK_PRISMARINE_STAIRS"
  - "DEAD_BRAIN_CORAL_BLOCK"
  - "DEAD_BUBBLE_CORAL_BLOCK"
  - "DEAD_FIRE_CORAL_BLOCK"
  - "DEAD_HORN_CORAL_BLOCK"
  - "DEAD_TUBE_CORAL_BLOCK"
  - "DIAMOND_BLOCK"
  - "DIAMOND_ORE"
  - "DIORITE"
  - "DIORITE_SLAB"
  - "DIORITE_STAIRS"
  - "DIORITE_WALL"
  - "DIRT"
  - "DRIED_KELP_BLOCK"
  - "EMERALD_BLOCK"
  - "EMERALD_ORE"
  - "ENCHANTING_TABLE"
  - "END_STONE"
  - "END_STONE_BRICK_SLAB"
  - "END_STONE_BRICK_STAIRS"
  - "END_STONE_BRICK_WALL"
  - "END_STONE_BRICKS"
  - "FARMLAND"
  - "FIRE_CORAL_BLOCK"
  - "GLOWSTONE"
  - "GOLD_BLOCK"
  - "GOLD_ORE"
  - "GRANITE"
  - "GRANITE_SLAB"
  - "GRANITE_STAIRS"
  - "GRANITE_WALL"
  - "GRASS_BLOCK"
  - "GRAVEL"
  - "GRAY_CONCRETE"
  - "GRAY_GLAZED_TERRACOTTA"
  - "GRAY_STAINED_GLASS"
  - "GRAY_TERRACOTTA"
  - "GRAY_WOOL"
  - "GREEN_CONCRETE"
  - "GREEN_GLAZED_TERRACOTTA"
  - "GREEN_STAINED_GLASS"
  - "GREEN_TERRACOTTA"
  - "GREEN_WOOL"
  - "HAY_BLOCK"
  - "HORN_CORAL_BLOCK"
  - "ICE"
  - "INFESTED_CHISELED_STONE_BRICKS"
  - "INFESTED_COBBLESTONE"
  - "INFESTED_CRACKED_STONE_BRICKS"
  - "INFESTED_MOSSY_STONE_BRICKS"
  - "INFESTED_STONE"
  - "INFESTED_STONE_BRICKS"
  - "IRON_BLOCK"
  - "IRON_ORE"
  - "JACK_O_LANTERN"
  - "JUNGLE_LEAVES"
  - "JUNGLE_LOG"
  - "JUNGLE_PLANKS"
  - "JUNGLE_SLAB"
  - "JUNGLE_STAIRS"
  - "JUNGLE_WOOD"
  - "LAPIS_BLOCK"
  - "LAPIS_ORE"
  - "LIGHT_BLUE_CONCRETE"
  - "LIGHT_BLUE_GLAZED_TERRACOTTA"
  - "LIGHT_BLUE_STAINED_GLASS"
  - "LIGHT_BLUE_TERRACOTTA"
  - "LIGHT_BLUE_WOOL"
  - "LIGHT_GRAY_CONCRETE"
  - "LIGHT_GRAY_GLAZED_TERRACOTTA"
  - "LIGHT_GRAY_STAINED_GLASS"
  - "LIGHT_GRAY_TERRACOTTA"
  - "LIGHT_GRAY_WOOL"
  - "LIME_CONCRETE"
  - "LIME_GLAZED_TERRACOTTA"
  - "LIME_STAINED_GLASS"
  - "LIME_TERRACOTTA"
  - "LIME_WOOL"
  - "MAGENTA_CONCRETE"
  - "MAGENTA_GLAZED_TERRACOTTA"
  - "MAGENTA_STAINED_GLASS"
  - "MAGENTA_TERRACOTTA"
  - "MAGENTA_WOOL"
  - "MAGMA_BLOCK"
  - "MOSSY_COBBLESTONE"
  - "MOSSY_COBBLESTONE_SLAB"
  - "MOSSY_COBBLESTONE_STAIRS"
  - "MOSSY_COBBLESTONE_WALL"
  - "MOSSY_STONE_BRICK_SLAB"
  - "MOSSY_STONE_BRICK_STAIRS"
  - "MOSSY_STONE_BRICK_WALL"
  - "MOSSY_STONE_BRICKS"
  - "MYCELIUM"
  - "NETHER_BRICK"
  - "NETHER_BRICK_SLAB"
  - "NETHER_BRICK_STAIRS"
  - "NETHER_BRICK_WALL"
  - "NETHER_BRICKS"
  - "NETHER_QUARTZ_ORE"
  - "NETHERRACK"
  - "OAK_LEAVES"
  - "OAK_LOG"
  - "OAK_PLANKS"
  - "OAK_SLAB"
  - "OAK_STAIRS"
  - "OAK_WOOD"
  - "OBSIDIAN"
  - "ORANGE_CONCRETE"
  - "ORANGE_GLAZED_TERRACOTTA"
  - "ORANGE_STAINED_GLASS"
  - "ORANGE_TERRACOTTA"
  - "ORANGE_WOOL"
  - "PACKED_ICE"
  - "PETRIFIED_OAK_SLAB"
  - "PINK_CONCRETE"
  - "PINK_GLAZED_TERRACOTTA"
  - "PINK_STAINED_GLASS"
  - "PINK_TERRACOTTA"
  - "PINK_WOOL"
  - "PODZOL"
  - "POLISHED_ANDESITE"
  - "POLISHED_ANDESITE_SLAB"
  - "POLISHED_ANDESITE_STAIRS"
  - "POLISHED_DIORITE"
  - "POLISHED_DIORITE_SLAB"
  - "POLISHED_DIORITE_STAIRS"
  - "POLISHED_GRANITE"
  - "POLISHED_GRANITE_SLAB"
  - "POLISHED_GRANITE_STAIRS"
  - "PRISMARINE"
  - "PRISMARINE_BRICK_SLAB"
  - "PRISMARINE_BRICK_STAIRS"
  - "PRISMARINE_BRICKS"
  - "PRISMARINE_SLAB"
  - "PRISMARINE_STAIRS"
  - "PRISMARINE_WALL"
  - "PUMPKIN"
  - "PURPLE_CONCRETE"
  - "PURPLE_GLAZED_TERRACOTTA"
  - "PURPLE_STAINED_GLASS"
  - "PURPLE_TERRACOTTA"
  - "PURPLE_WOOL"
  - "PURPUR_BLOCK"
  - "PURPUR_PILLAR"
  - "PURPUR_SLAB"
  - "PURPUR_STAIRS"
  - "QUARTZ_BLOCK"
  - "QUARTZ_PILLAR"
  - "QUARTZ_SLAB"
  - "QUARTZ_STAIRS"
  - "RED_CONCRETE"
  - "RED_GLAZED_TERRACOTTA"
  - "RED_MUSHROOM_BLOCK"
  - "RED_NETHER_BRICK_SLAB"
  - "RED_NETHER_BRICK_STAIRS"
  - "RED_NETHER_BRICK_WALL"
  - "RED_NETHER_BRICKS"
  - "RED_SAND"
  - "RED_SANDSTONE"
  - "RED_SANDSTONE_SLAB"
  - "RED_SANDSTONE_STAIRS"
  - "RED_SANDSTONE_WALL"
  - "RED_STAINED_GLASS"
  - "RED_TERRACOTTA"
  - "RED_WOOL"
  - "REDSTONE_BLOCK"
  - "REDSTONE_ORE"
  - "SAND"
  - "SANDSTONE"
  - "SANDSTONE_SLAB"
  - "SANDSTONE_STAIRS"
  - "SANDSTONE_WALL"
  - "SEA_LANTERN"
  - "SMOOTH_QUARTZ"
  - "SMOOTH_QUARTZ_SLAB"
  - "SMOOTH_QUARTZ_STAIRS"
  - "SMOOTH_RED_SANDSTONE"
  - "SMOOTH_RED_SANDSTONE_SLAB"
  - "SMOOTH_RED_SANDSTONE_STAIRS"
  - "SMOOTH_SANDSTONE"
  - "SMOOTH_SANDSTONE_SLAB"
  - "SMOOTH_SANDSTONE_STAIRS"
  - "SMOOTH_STONE"
  - "SMOOTH_STONE_SLAB"
  - "SNOW_BLOCK"
  - "SOUL_SAND"
  - "SPONGE"
  - "SPRUCE_LEAVES"
  - "SPRUCE_LOG"
  - "SPRUCE_PLANKS"
  - "SPRUCE_SLAB"
  - "SPRUCE_STAIRS"
  - "SPRUCE_WOOD"
  - "STONE"
  - "STONE_BRICK_SLAB"
  - "STONE_BRICK_STAIRS"
  - "STONE_BRICK_WALL"
  - "STONE_BRICKS"
  - "STONE_SLAB"
  - "STONE_STAIRS"
  - "STRIPPED_ACACIA_LOG"
  - "STRIPPED_ACACIA_WOOD"
  - "STRIPPED_BIRCH_LOG"
  - "STRIPPED_BIRCH_WOOD"
  - "STRIPPED_DARK_OAK_LOG"
  - "STRIPPED_DARK_OAK_WOOD"
  - "STRIPPED_JUNGLE_LOG"
  - "STRIPPED_JUNGLE_WOOD"
  - "STRIPPED_OAK_LOG"
  - "STRIPPED_OAK_WOOD"
  - "STRIPPED_SPRUCE_LOG"
  - "STRIPPED_SPRUCE_WOOD"
  - "TERRACOTTA"
  - "TNT"
  - "TUBE_CORAL_BLOCK"
  - "WET_SPONGE"
  - "WHITE_CONCRETE"
  - "WHITE_GLAZED_TERRACOTTA"
  - "WHITE_STAINED_GLASS"
  - "WHITE_TERRACOTTA"
  - "WHITE_WOOL"
  - "YELLOW_CONCRETE"
  - "YELLOW_GLAZED_TERRACOTTA"
  - "YELLOW_STAINED_GLASS"
  - "YELLOW_TERRACOTTA"
  - "YELLOW_WOOL"
  
